PPKM = read.delim("clipboard")
View(PPKM)
str(PPKM)
install.packages("e1071")
install.packages("caret")
install.packages("proxy")
install.packages("plyr")
install.packages("gower")
install.packages("prodlim")
install.packages("ipred")
install.packages("lubridate")
library(e1071)
library(caret)
library(proxy)
library(plyr)
library(gower)
library(prodlim)
library(ipred)
sampel=sample(1:nrow(PPKM),0.8*nrow(PPKM),replace = TRUE)
training=data.frame(PPKM)[sampel,]
testing=data.frame(PPKM)[-sampel,]
modelNB=naiveBayes(Klasifikasi~.,data = training)
prediksi=predict(modelNB,testing)
hasil=confusionMatrix(table(prediksi,testing$Klasifikasi))
